language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - OC_PASS=ampache
  matrix:
    - DB=mysql;CLOUD=owncloud
    - DB=pgsql;CLOUD=owncloud
    - DB=mysql;CLOUD=nextcloud
    - DB=pgsql;CLOUD=nextcloud

matrix:
  include:
    #- php: 5.6
      #env: DB=mysql CLOUD=owncloud CORE_BRANCH=stable8.1
    - php: 7
      env: DB=mysql CLOUD=owncloud CORE_BRANCH=stable8.2
    - php: 7
      env: DB=mysql CLOUD=owncloud CORE_BRANCH=stable9
    - php: 7
      env: DB=mysql CLOUD=owncloud CORE_BRANCH=stable9.1
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - "/tmp/downloadedData"

before_install:
  - php --info
  # Set up DB
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE oc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON oc_autotest.* TO 'oc_autotest'@'localhost';"; fi

  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ]; then curl -s -o $HOME/.phpenv/versions/5.4/bin/phpunit https://phar.phpunit.de/phpunit-4.8.9.phar; fi;"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ]; then chmod +x $HOME/.phpenv/versions/5.4/bin/phpunit; fi;"
  - composer self-update
  - composer install
  - cd ..
  - sh -c "if [ '$CLOUD' = 'nextcloud' ]; then git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core; fi;"
  - sh -c "if [ '$CLOUD' = 'owncloud' ]; then git clone https://github.com/owncloud/core.git --recursive --depth 1 -b $CORE_BRANCH core; fi;"
  - sh -c "if [ '$CLOUD' = 'owncloud' ] && [ $CORE_BRANCH = 'master' ]; then cd core && make; fi;"
  - sh -c "if ([ '$CLOUD' = 'owncloud' ] && [ $CORE_BRANCH != 'master' ]) || [ '$CLOUD' = 'nextcloud' ]; then cd core && git submodule update --init; fi;"
  - mv music core/apps/

before_script:
  # setup ownCloud
  - php -f core/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
  - php -f core/occ app:enable music
  - php -f core/occ user:add ampache --password-from-env
  # download test data (only if not cached already)
  - core/apps/music/tests/downloadTestData.sh ${TRAVIS_BUILD_DIR}/../core/data/ampache
  - php -f core/occ files:scan ampache
  - php -f core/occ music:scan ampache
  # add Ampache API key with ampache as password for user ampache
  - bash -c "if [ '$DB' == 'sqlite' ]; then sqlite3 data/owncloud.db 'INSERT INTO oc_music_ampache_users (user_id, hash) VALUES (\"ampache\", \"3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18\");'; fi"
  - bash -c "if [ '$DB' == 'mysql' ]; then mysql -u oc_autotest oc_autotest -e 'INSERT INTO oc_music_ampache_users (user_id, hash) VALUES (\"ampache\", \"3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18\");'; fi"
  - bash -c "if [ '$DB' == 'pgsql' ]; then psql -U oc_autotest -d oc_autotest -w -c \"INSERT INTO oc_music_ampache_users (user_id, hash) VALUES ('ampache', '3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18');\"; fi"
  - cd core
  - php -S localhost:8888 -t . &
  - cd apps/music
  - cp tests/behat.yml.travis tests/behat.yml

script:
  - phpunit --coverage-clover clover-unit.xml --configuration tests/php/unit/phpunit.xml tests/php/unit
  - phpunit --coverage-clover clover-integration.xml --configuration tests/php/integration/phpunit.xml tests/php/integration
  - cd tests && ../vendor/bin/behat

  # Create coverage report
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == '7' ] && [ '$DB' == 'mysql' ] && [ '$CLOUD' = 'owncloud' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == '7' ] && [ '$DB' == 'mysql' ] && [ '$CLOUD' = 'owncloud' ]; then php ocular.phar code-coverage:upload --format=php-clover ../clover-unit.xml; fi"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == '7' ] && [ '$DB' == 'mysql' ] && [ '$CLOUD' = 'owncloud' ]; then php ocular.phar code-coverage:upload --format=php-clover ../clover-integration.xml; fi"

  # debug section to check what went wrong
  - curl http://admin:admin@localhost:8888/index.php
  - curl http://admin:admin@localhost:8888/index.php/apps/music/
  - cat ../../../data/${CLOUD}.log

